# Generated by Django 4.0.5 on 2022-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('zakaz_field', models.CharField(db_column='заказ_№', max_length=40)),
                ('stoimostvdol_field', models.IntegerField(blank=True, db_column='стоимость_в_$', null=True)),
                ('srok_postavki', models.CharField(blank=True, db_column='срок_поставки', max_length=30, null=True)),
                ('stoimostvrub', models.IntegerField(blank=True, db_column='стоимость_в_rub', null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
    ]
